name: trigger jenkins webhook on Push to Master
on:
  push:
    branches:
      - master
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps: 
    - name: call jenkins webhook
      shell: bash
      env:
        URL: ${{ vars.JENKINS_WEBHOOK_URL }}
        USERNAME: ${{ secrets.JENKINS_USERNAME }}
        PASSWORD: ${{ secrets.JENKINS_API_KEY }}
        TOKEN: ${{ secrets.JENKINS_WEBHOOK_TOKEN }}
        JOB_NAME: ${{ vars.JENKINS_JOB_NAME }}
      run: curl -X POST -L --user $USERNAME:$PASSWORD $URL/job/$JOB_NAME/build?token=$TOKEN
